---
- hosts: all
  connection: local
  name: Get BIOS attributes
  gather_facts: False

  vars:
    datatype: BiosAttributes

  tasks:

  - name: Define output file
    include_tasks: create_output_file.yml

  - name: Get BIOS attributes
    redfish_info:
      category: Systems
      command: GetBiosAttributes
      baseuri: "https://192.168.23.77"
      username: "USERID"
      password: "PA$$WORD987"
      timeout: 20
    register: result

  - name: Copy results to output file
    copy:
      content: "{{ result | to_nice_json }}"
      dest: "{{ template }}.json"
