---
- hosts: all
  connection: local
  name: Get BIOS attributes
  gather_facts: False

  vars:
    datatype: BiosAttributes

  tasks:

  - name: Get BIOS attributes
    redfish_info:
      category: Systems
      command: GetBiosAttributes
      baseuri: "192.168.23.77"
      username: "USERID"
      password: "PA$$WORD987"
      timeout: 20
    register: result

  - name: Print result
    debug:
      msg: "{{ result }}"
