---
- hosts: all
  connection: local
  name: Get BIOS attributes
  gather_facts: False

  vars:
    datatype: BiosAttributes

  tasks:

  - name: Set BIOS attribute
    redfish_config:
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
      command: SetBiosAttributes
      bios_attribute_name: "IPv6Enabled"
      bios_attribute_value: 'false'
      category: Managers

