---
- hosts: all
  connection: local
  name: Get BIOS attributes
  gather_facts: False

  vars:
    datatype: BiosAttributes

  tasks:

  - name: Set Manager NIC
    redfish_config:
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
      command: SetBiosAttributes
      bios_attribute_name: "Memory_2xRefreshRate"
      bios_attribute_value: 'Auto'
      category: Systems

  - name: Reboot system to apply new BIOS settings
    redfish_config:
      category: Systems
      command: GracefulRestart
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
