---
- hosts: all
  connection: local
  name: Get BIOS attributes
  gather_facts: False

  vars:
    datatype: BiosAttributes

  tasks:

  - name: Set Manager NIC
    redfish_config:
      category: Manager
      command: SetManagerNic
      bios_atribute_name: IPV6Enabled
      bios_atribute_value: false
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
