---
- hosts: all
  connection: local
  name: Get BIOS attributes
  gather_facts: False

  vars:
    datatype: BiosAttributes

  tasks:

  - name: Set Manager NIC
    redfish_config:
      category: Managers
      command: SetBiosAttributes
      bios_attributes:
        DHCPv4:
          DHCPEnabled: true
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
