---
- hosts: all
  connection: local
  name: Get BIOS attributes
  gather_facts: False

  vars:
    datatype: BiosAttributes

  tasks:

  - name: Set Manager NIC
    redfish_config:
      category: Managers
      baseuri: "https://{{ baseuri }}/redfish/v1/Managers/1/EthernetInterfaces/NIC"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      payload:
        Attributes:
          IPv6Enabled: false
