---
- hosts: all
  connection: local
  name: Get BIOS attributes
  gather_facts: False

  vars:
    datatype: BiosAttributes

  tasks:

  - name: Set Manager NIC
    redfish_config:
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
      bios_attribute_name: "IPv6Enabled"
      bios_attribute_value: "false"
      category: "BIOS"
