---
- hosts: all
  connection: local
  name: Get cpu inventory
  gather_facts: False

  vars:
    datatype: CpuInventory

  tasks:

  - name: Get cpu inventory
    redfish_info:
      category: Systems
      command: GetCpuInventory
      timeout: 20
    register: result

  - name: Print result
    debug:
      msg: "{{ result }}"
